WIP upload profile images
RIFT-tokyo/transcendence-env pull request #12
Opened 2022-03-01 13:09 UTC by sasakiyudai

## チケットへのリンク

## やったこと

## やらないこと

## テスト

## その他

2022-03-02 13:05 UTC, tkomatsu requested changes

2022-03-02 13:05 UTC, tkomatsu commented on docker-compose.yaml
> +      - './docker/minio/policies:/policies'
localのディレクトリをマウントするんじゃなくて、docker volumeを作ってマウントして欲しいな

2022-03-02 13:05 UTC, tkomatsu commented on docker-compose.yaml
> +      - MINIO_SECRET_KEY=minio123
.envファイルに突っ込んで欲しいな

2022-03-02 13:05 UTC, tkomatsu commented on docker/minio/policies/buckets/static/policy.json
> +{
このファイルだけ設定に必要ってことだと思うんだけど、`minio`ディレクトリ作って、その中に入れて欲しいな
docker-compose.ymlでそれだけマウントする感じにして欲しいな

2022-03-03 12:07 UTC, sasakiyudai commented on docker-compose.yaml
> +      - MINIO_SECRET_KEY=minio123
[c049306](https://github.com/RIFT-tokyo/transcendence-env/pull/12/commits/c04930685788a6219716632939d31e0f7b72e6e0)
でしました

2022-03-03 12:08 UTC, sasakiyudai commented on docker/minio/policies/buckets/static/policy.json
> +{
[6afa3cc](https://github.com/RIFT-tokyo/transcendence-env/pull/12/commits/6afa3cc13f206fb7b5de43c2a560988bf5086d97)
exportも初期データ投入 & /data直下にstaticディレクトリ追加っていう役割があるので2つ用意しました。

2022-03-03 12:09 UTC, sasakiyudai commented on docker-compose.yaml
> +      - './docker/minio/policies:/policies'
[6afa3cc](https://github.com/RIFT-tokyo/transcendence-env/pull/12/commits/6afa3cc13f206fb7b5de43c2a560988bf5086d97)
dataとconfigに関して別にホストOS側でいらんと思って消したんですけどこれで良いですかね？
あとexportも残しました。理由は2個下のreviewのやつに書いてます。

2022-03-03 13:35 UTC, tkomatsu commented on docker-compose.yaml
> +      - './minio/policies:/policies'
名前付きのDocker Volumeを作るようにして欲しいです。
https://matsuand.github.io/docs.docker.jp.onthefly/storage/volumes/#use-a-volume-with-docker-compose

pgadminやpostgresのデータ用ボリュームと同様に、docker-compose内でコンテナのボリュームを立ち上げるってことです！
今の構成の場合、リポジトリと同じディレクトリにデータが保存されるようになってしまいます。
データを削除してやり直したい時（コンテナはこれを気軽にできるのがメリット）に手動でボリュームを削除することなく、dockerのコマンドでやり切れることが望ましいです。
サンプルデータだけ追加するのであれば、
```yml
services:
  minio:
    volumes:
      - 'transcendence-minio-data:/export/static'
      - './minio/transcendence.jpg:/export/static/transcendence.jpg`
```
とすると、サンプルデータ以外のファイルは名前つきdocker volumeに保存されるようになるはずです。
staticディレクトリを作成することは1つ目で、サンプルデータの追加は2つ目で解決できてるはず。

`policy.json`に関しては、リポジトリ内に`/minio/policy.json`で保存し、docker-compose.yml内で
```yml
volume:
  - './minio/policy.json:/policies/buckets/static/policy.json`
```
って感じで配置してもらえると！

2022-03-03 13:35 UTC, tkomatsu commented on docker-compose.yaml
> -    driver: local
これって消した理由あったら知りたい

2022-03-04 10:41 UTC, sasakiyudai commented on docker-compose.yaml
> -    driver: local
理由は以下の3つです
・デフォルトがlocal
・明示的に書くのあんまり見たことない
・複数あると二倍になり冗長で読みにくい

2022-03-04 11:29 UTC, sasakiyudai commented on docker-compose.yaml
> +      - './minio/policies:/policies'
[3ecfb41](https://github.com/RIFT-tokyo/transcendence-env/pull/12/commits/3ecfb41276f59b3de979823fec71bf9ad63218f8)
[9aa6fe4](https://github.com/RIFT-tokyo/transcendence-env/pull/12/commits/9aa6fe45dd4074a7a7d5a680b1b5c4f75ae587a5)
でやりました

2022-03-04 11:41 UTC, tkomatsu commented on docker-compose.yaml
> -    driver: local
知らんかった
最初書いた時もそんなもんかーと思って書いてたから知見！
ありがたや

2022-03-04 11:42 UTC, tkomatsu approved these changes
LGTM！
すごい！便利！

2022-03-04 11:42 UTC, merged