persist with volume
RIFT-tokyo/transcendence-env pull request #17
Opened 2022-03-18 11:36 UTC by sasakiyudai

## チケットへのリンク
fix #16 
## やったこと
minioの/dataをdocker volumeに
## やらないこと

## テスト

## その他

2022-03-18 23:59 UTC, tkomatsu requested changes
プロフィール設定画面からリクエスト送ると正しくアップロードできなくなってます。

2022-03-19 01:08 UTC, sasakiyudai commented
syuusei [60bd309](https://github.com/RIFT-tokyo/transcendence-env/pull/17/commits/60bd309044ad7cd1bc750de9440c7d8000b15b5f)

2022-03-19 01:12 UTC, tkomatsu requested changes
`docker compose down && docker compose up`で以下のエラーが出てコンテナが立ち上がらないですー
```log
transcendence-env-minio-1  | mkdir: cannot create directory '/data/static': File exists
```

2022-03-19 01:36 UTC, tkomatsu approved these changes
LGTM

2022-03-19 01:36 UTC, merged